#CONFIGURAÇÕES GERAIS

# Backend: glx é geralmente mais rápido em GPUs modernas
backend = "xrender";

# Ativar VSync para reduzir screen tearing
vsync = true;

# Taxa de refresh (0 = detectar automaticamente)
refresh-rate = 0;

#LOGS

# Nível de log (trace, debug, info, warn, error)
log-level = "warn";

# Usar danified para melhor performance
use-damage = true;
